services:
  db:
    container_name: pi-go-bot-dev-postgres
    build: 
      context: .
      dockerfile: ./postgres/Dockerfile
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres/DB:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data
