name: Build on Push  # ワークフローの名前

on: push  # push イベントでトリガー

jobs:
  build:
    runs-on: ubuntu-latest  # ビルドは GitHub Hosted Runner 上で行う
    steps:
      - name: ソースコードをチェックアウト
        uses: actions/checkout@v4

      - name: Go のセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 必要な Go のバージョンを指定

      - name: 依存関係の取得
        run: go mod tidy

      - name: Go のテスト実行
        run: go test -v ./...

      - name: ARM64 用にコンパイル
        run: |
          GOOS=linux GOARCH=arm64 go build -o myapp
