name: Build and Deploy for ARM64

on: [ workflow_dispatch ]

jobs:
  build:
    if: github.actor == 'aktnb' && github.ref_name == 'master'  # 特定のユーザーが main ブランチに push した場合のみ実行
    runs-on: self-hosted  # ビルドは GitHub Hosted Runner 上で行う
    steps:
      - name: ソースコードをチェックアウト
        uses: actions/checkout@v4

      - name: Go のセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'  # 必要な Go のバージョンを指定

      - name: 依存関係の取得
        run: go mod tidy

      - name: Go のテスト実行
        run: go test -v ./...

      - name: ARM64 用にコンパイル
        run: |
          GOOS=linux GOARCH=arm64 go build -o myapp

      - name: サービスを停止
        run: sudo systemctl stop pigobot

      - name: バイナリを配置
        run: cp myapp ~/

      - name: 実行権限を付与
        run: chmod +x ~/myapp

      - name: サービスを起動
        run: sudo systemctl restart pigobot
